DELETE http://localhost:3001/api/blogs/63906e1f5021b182a8d313f2
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pbmVydmEiLCJpZCI6IjYzOGY0MjBmZTlkNTViYmYyM2IwYTRhNCIsImlhdCI6MTY3MDQwODg5Nn0.AQ2kyJp9Ze9bRiKKPbaT5cr1Q_d3cbw0fVU4eeM8W3M